[package]
name = "libxml"
version = "0.0.743"
authors = ["Jan Frederik Schaefer <j.schaefer@jacobs-university.de>", "Deyan Ginev <d.ginev@jacobs-university.de>"]
description = "A Rust wrapper for libxml2"
repository = "https://github.com/KWARC/rust-libxml"
documentation = "http://kwarc.github.io/rust-libxml/libxml/index.html"
readme = "README.md"
license = "MIT"

build = "build.rs"
exclude = [
  "scripts/*"
]

[dependencies]
libc = "~0.1"

[build-dependencies]
gcc = "0.3.21"

[lib]
name = "libxml"
