[package]
name = "libxml"
version = "0.0.2"

authors = ["Jan Frederik Schaefer <j.schaefer@jacobs-university.de>", "Deyan Ginev <d.ginev@jacobs-university.de>"]
description = "A Rust wrapper for libxml2"
repository = "https://github.com/KWARC/rust-libxml"
readme = "README.md"
license = "GPL-2.0"

build = "build.rs"

[dependencies]
libc = "~0.1"

[build-dependencies]
gcc = "0.3.21"

[lib]
name = "libxml"

